package org.myproject.parking.model;

import lombok.*;
import org.myproject.parking.pricing.PricingConfig;

import java.util.List;


@EqualsAndHashCode(of = "parkingLotId")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ParkingLot {
    private Integer parkingLotId;    //parkingId will be autogenerated by DB
    private String name;        //help find and identify parking
    private List<ParkingSpot> spots;

    private PricingConfig pricingConfig; //depends on the certain implementation

    public ParkingLot(String name, List<ParkingSpot> spots, PricingConfig pricingConfig) {
        this.name = name;
        this.spots = spots;
        this.pricingConfig = pricingConfig;
    }
}
