package org.myproject.parking.model;

import lombok.*;
import org.myproject.parking.model.vehicle.VehicleType;
import org.myproject.parking.pricing.PolicyType;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Random;


@EqualsAndHashCode(of = "parkingId")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class Parking {
    private Integer parkingId;
    private List<ParkingSpot> spots;
    private Long location; //help find parking

    private PolicyType pricingPolicyType; //depends on the certain implementation

    public Parking(Map<VehicleType, Integer> spotsNumberByType, int price) {
        spots = new ArrayList<>();
        int i = 1; // will be autoincrement in DB
        for (Map.Entry<VehicleType, Integer> ent : spotsNumberByType.entrySet()) {
            for (int c = 0; c < ent.getValue(); c++) {
                spots.add(new ParkingSpot(i, ent.getKey(), price));
            }
        }
        pricingPolicyType = PolicyType.STANDARD;
        parkingId = new Random().nextInt();
        //parkingId will be autogenerated
    }
}
